[light_sources]
	water_sensitive_check = true
	self = true
	block_entities = true
	entities = true

			[light_sources.settings.entities.minecraft]
				chicken = true
				panda = true
				bee = true
				axolotl = true
				donkey = true
				cow = true
				tropical_fish = true
				chest_minecart = true
				fox = true
				pig = true
				slime = true
				pillager = true
				skeleton = true
				llama = true
				bat = true
				frog = true
				armadillo = true
				rabbit = true
				zombie = true
				ender_pearl = true
				firework_rocket = true
				drowned = true
				sheep = true
				experience_orb = true
				player = true
				dolphin = true
				pufferfish = true
				item = true
				stray = true
				turtle = true
				shulker = true
				wolf = true
				salmon = true
				zombie_villager = true
				goat = true
				ocelot = true
				polar_bear = true
				item_frame = true
				horse = true
				ender_dragon = true
				glow_squid = true
				cod = true
				witch = true
				squid = true
				spider = true
				parrot = true
				creeper = true
				enderman = true

			[light_sources.settings.entities.friendsandfoes]
				mauler = true
				rascal = true

			[light_sources.settings.entities.variantsandventures]
				gelid = true

			[light_sources.settings.entities.hybrid-aquatic]
				vampire_crab = true
				barrel_jellyfish = true
				zebra_danio = true
				sea_urchin = true
				flower_crab = true
				compass_jellyfish = true
				anglerfish = true
				cauliflower_jellyfish = true
				tiger_barb = true
				sea_nettle = true
				seahorse = true
				barreleye = true
				blue_tang = true
				rockfish = true
				lightfoot_crab = true
				mahimahi = true
				toadfish = true
				piranha = true
				lobster = true
				gourami = true
				glowing_sucker_octopus = true
				dragonfish = true
				stonefish = true
				needlefish = true
				mauve_stinger = true
				shrimp = true
				ghost_crab = true
				moon_jellyfish = true
				nudibranch = true
				crayfish = true
				vampire_squid = true
				unicorn_fish = true
				cowfish = true
				clownfish = true
				cuttlefish = true
				discus = true
				atolla_jellyfish = true
				umbrella_octopus = true
				starfish = true
				blue_jellyfish = true
				coconut_crab = true
				ratfish = true
				hermit_crab = true
				firefly_squid = true
				horseshoe_crab = true
				sea_cucumber = true
				yellowfin_tuna = true
				opah = true
				frilled_shark = true
				fiddler_crab = true
